'use client'

import { useState } from 'react'
import { FileText, Download, Calendar, Check, FileDown } from 'lucide-react'
import { reports, hosts, complianceRules, issues, type Report } from '@/lib/data'
import { cn } from '@/lib/utils'
import { reportsStorage } from '@/lib/storage'
import { PDFExporter, type PDFReportData } from '@/lib/pdf-exporter'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Checkbox } from '@/components/ui/checkbox'

export function ReportsContent() {
  const [reportName, setReportName] = useState(`Compliance Report - ${new Date().toLocaleDateString('en-GB').replace(/\//g, '/')}`)
  const [startDate, setStartDate] = useState('2026-01-27')
  const [endDate, setEndDate] = useState('2026-02-03')
  const [selectedHosts, setSelectedHosts] = useState('all')
  const [includeRawPayload, setIncludeRawPayload] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [recentReports, setRecentReports] = useState<Report[]>(reports)

  const handleGenerateReport = () => {
    setIsGenerating(true)
    
    // Simulate report generation
    setTimeout(() => {
      const newReport: Report = {
        id: String(Date.now()),
        name: reportName,
        date: new Date().toLocaleDateString('en-GB').replace(/\//g, '/'),
        hosts: selectedHosts === 'all' ? hosts.length : parseInt(selectedHosts),
        status: 'Completed',
      }
      setRecentReports((prev) => [newReport, ...prev])
      setIsGenerating(false)
    }, 2000)
  }

  const handleDownload = (report: Report) => {
    // Generate comprehensive PDF report data
    const criticalIssues = issues.filter(i => i.severity === 'critical')
    const highIssues = issues.filter(i => i.severity === 'high')
    
    const pdfData: PDFReportData = {
      title: report.name,
      subtitle: 'RACAP Compliance Report - DigiTruce Security Platform',
      date: new Date().toLocaleString('en-IN'),
      metadata: {
        'Report ID': report.id,
        'Generated': report.date,
        'Hosts Included': report.hosts.toString(),
        'Status': report.status,
        'Generated By': 'RACAP System'
      },
      sections: [
        {
          title: 'Executive Summary',
          content: [
            'This report provides a comprehensive overview of the compliance status across all monitored hosts in the organization.',
            `Total Hosts Scanned: ${hosts.length}`,
            `Total Compliance Rules: ${complianceRules.length}`,
            `Critical Issues: ${criticalIssues.length}`,
            `High Priority Issues: ${highIssues.length}`
          ]
        },
        {
          title: 'Compliance Score Overview',
          content: [
            'Average Compliance Score: 82%',
            'Improvement from Last Period: +3%',
            'Total Failed Controls: 56',
            'Total Passed Controls: 234'
          ]
        },
        {
          title: 'Top Failed Controls',
          type: 'table',
          content: criticalIssues.slice(0, 10).map(issue => ({
            'Rule ID': issue.ruleId,
            'Framework': issue.framework,
            'Severity': issue.severity,
            'Hosts Affected': issue.hostsAffected,
            'Status': issue.status
          }))
        },
        {
          title: 'Host Summary',
          type: 'table',
          content: hosts.slice(0, 15).map(host => ({
            'Hostname': host.hostname,
            'OS': host.os,
            'Score': `${host.score}%`,
            'Critical Failed': host.criticalFailed || 0,
            'Last Seen': host.lastSeen
          }))
        },
        {
          title: 'Recommendations',
          type: 'list',
          content: [
            'Enable automatic security updates on all affected hosts',
            'Implement strong password complexity requirements across all systems',
            'Enable comprehensive user account monitoring and auditing',
            'Review and update firewall rules for critical infrastructure',
            'Schedule regular compliance assessments and remediation cycles',
            'Conduct security awareness training for all administrative staff',
            'Implement multi-factor authentication for administrative access'
          ]
        }
      ]
    }
    
    // Export to PDF (opens print dialog)
    PDFExporter.exportToPDF(pdfData)
  }

  const handleDownloadText = (report: Report) => {
    // Generate text version
    const pdfData: PDFReportData = {
      title: report.name,
      date: new Date().toLocaleString('en-IN'),
      metadata: {
        'Report ID': report.id,
        'Generated': report.date,
        'Hosts': report.hosts.toString()
      },
      sections: [
        {
          title: 'Executive Summary',
          content: 'This report provides a comprehensive overview of the compliance status.'
        }
      ]
    }
    
    PDFExporter.downloadAsText(pdfData, report.name.replace(/\s+/g, '-'))
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-foreground">Reports</h1>
        <p className="mt-1 text-muted-foreground">
          Generate and download compliance reports
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Generate New Report Form */}
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-xl border border-border bg-card p-6">
            <h2 className="text-xl font-semibold text-foreground mb-6">Generate New Report</h2>
            
            <div className="space-y-5">
              {/* Report Name */}
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-2">
                  Report Name
                </label>
                <input
                  type="text"
                  value={reportName}
                  onChange={(e) => setReportName(e.target.value)}
                  className="w-full rounded-lg border border-border bg-secondary py-2.5 px-4 text-sm placeholder:text-muted-foreground focus:border-cyan focus:outline-none focus:ring-1 focus:ring-cyan"
                />
              </div>

              {/* Date Range */}
              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-2">
                    Start Date
                  </label>
                  <div className="relative">
                    <input
                      type="date"
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                      className="w-full rounded-lg border border-border bg-secondary py-2.5 px-4 text-sm focus:border-cyan focus:outline-none focus:ring-1 focus:ring-cyan"
                    />
                    <Calendar className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground pointer-events-none" />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-muted-foreground mb-2">
                    End Date
                  </label>
                  <div className="relative">
                    <input
                      type="date"
                      value={endDate}
                      onChange={(e) => setEndDate(e.target.value)}
                      className="w-full rounded-lg border border-border bg-secondary py-2.5 px-4 text-sm focus:border-cyan focus:outline-none focus:ring-1 focus:ring-cyan"
                    />
                    <Calendar className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground pointer-events-none" />
                  </div>
                </div>
              </div>

              {/* Select Hosts */}
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-2">
                  Select Hosts
                </label>
                <Select value={selectedHosts} onValueChange={setSelectedHosts}>
                  <SelectTrigger className="w-full border-border bg-secondary">
                    <SelectValue placeholder="Select hosts" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Hosts ({hosts.length})</SelectItem>
                    <SelectItem value="critical">Critical Hosts Only</SelectItem>
                    <SelectItem value="non-compliant">Non-Compliant Hosts</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Include Raw Payload */}
              <div className="flex items-center gap-3">
                <Checkbox
                  id="raw-payload"
                  checked={includeRawPayload}
                  onCheckedChange={(checked) => setIncludeRawPayload(checked as boolean)}
                />
                <label htmlFor="raw-payload" className="text-sm text-muted-foreground cursor-pointer">
                  Include raw scan payload (increases file size)
                </label>
              </div>

              {/* Generate Button */}
              <button
                onClick={handleGenerateReport}
                disabled={isGenerating}
                className={cn(
                  'w-full flex items-center justify-center gap-2 rounded-lg py-3 text-sm font-medium transition-colors',
                  isGenerating
                    ? 'bg-cyan/50 text-black/50 cursor-not-allowed'
                    : 'bg-cyan text-black hover:bg-cyan/90'
                )}
              >
                <FileText className="h-4 w-4" />
                {isGenerating ? 'Generating Report...' : 'Generate Report'}
              </button>
            </div>
          </div>

          {/* Recent Reports */}
          <div className="rounded-xl border border-border bg-card p-6">
            <h2 className="text-xl font-semibold text-foreground mb-4">Recent Reports</h2>
            <div className="space-y-3">
              {recentReports.map((report) => (
                <div
                  key={report.id}
                  className="flex items-center justify-between rounded-lg border border-border bg-secondary/50 p-4"
                >
                  <div className="flex items-center gap-4">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-secondary">
                      <FileText className="h-5 w-5 text-muted-foreground" />
                    </div>
                    <div>
                      <h3 className="font-medium text-foreground">{report.name}</h3>
                      <p className="text-sm text-muted-foreground">
                        <Calendar className="inline h-3 w-3 mr-1" />
                        {report.date} &middot; {report.hosts} hosts
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="flex items-center gap-1 rounded-full border border-green/50 px-3 py-1 text-xs font-medium text-green">
                      <Check className="h-3 w-3" />
                      {report.status}
                    </span>
                    <div className="flex gap-2">
                      <button
                        onClick={() => handleDownload(report)}
                        className="flex items-center gap-2 rounded-lg bg-cyan px-4 py-2 text-sm font-medium text-black hover:bg-cyan/90 transition-colors"
                      >
                        <FileDown className="h-4 w-4" />
                        PDF
                      </button>
                      <button
                        onClick={() => handleDownloadText(report)}
                        className="flex items-center gap-2 rounded-lg bg-secondary px-4 py-2 text-sm font-medium text-foreground hover:bg-secondary/80 transition-colors"
                      >
                        <Download className="h-4 w-4" />
                        Text
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Report Details Sidebar */}
        <div>
          <div className="rounded-xl border border-border bg-card p-6 sticky top-24">
            <h2 className="text-lg font-semibold text-foreground mb-4">Report Details</h2>
            
            <div className="space-y-4">
              <div>
                <h3 className="text-sm font-medium text-foreground mb-2">Included Information:</h3>
                <ul className="space-y-1.5 text-sm text-muted-foreground">
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground" />
                    Executive summary
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground" />
                    Compliance score trends
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground" />
                    Failed controls breakdown
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground" />
                    Host-by-host details
                  </li>
                  <li className="flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground" />
                    Remediation recommendations
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="text-sm font-medium text-foreground mb-1">Format:</h3>
                <p className="text-sm text-muted-foreground">PDF (portable document)</p>
              </div>

              <div>
                <h3 className="text-sm font-medium text-foreground mb-1">Estimated Size:</h3>
                <p className="text-sm text-muted-foreground">~2 MB</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
