// PDF Export Utility using browser's print functionality
// This creates a properly formatted HTML that can be printed to PDF

export interface PDFReportData {
  title: string
  subtitle?: string
  date: string
  sections: PDFSection[]
  metadata?: {
    generatedBy?: string
    organization?: string
    location?: string
    [key: string]: any
  }
}

export interface PDFSection {
  title: string
  content: string | string[] | { [key: string]: any }[]
  type?: 'text' | 'table' | 'list' | 'chart'
}

export class PDFExporter {
  private static readonly styles = `
    <style>
      @media print {
        body { margin: 0; padding: 0; }
        .page-break { page-break-after: always; }
        .no-print { display: none; }
      }
      
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
        line-height: 1.6;
        color: #1a1a1a;
        max-width: 210mm;
        margin: 0 auto;
        padding: 20mm;
        background: white;
      }
      
      h1 {
        color: #06b6d4;
        font-size: 28px;
        margin-bottom: 8px;
        border-bottom: 3px solid #06b6d4;
        padding-bottom: 10px;
      }
      
      h2 {
        color: #0891b2;
        font-size: 20px;
        margin-top: 24px;
        margin-bottom: 12px;
        border-bottom: 2px solid #e5e7eb;
        padding-bottom: 6px;
      }
      
      h3 {
        color: #334155;
        font-size: 16px;
        margin-top: 16px;
        margin-bottom: 8px;
      }
      
      .metadata {
        background: #f8fafc;
        border-left: 4px solid #06b6d4;
        padding: 12px 16px;
        margin: 16px 0;
        font-size: 14px;
      }
      
      .metadata-item {
        display: flex;
        justify-content: space-between;
        margin: 4px 0;
      }
      
      .metadata-label {
        font-weight: 600;
        color: #64748b;
      }
      
      table {
        width: 100%;
        border-collapse: collapse;
        margin: 16px 0;
        font-size: 14px;
      }
      
      th {
        background: #f1f5f9;
        color: #334155;
        font-weight: 600;
        text-align: left;
        padding: 12px;
        border: 1px solid #e2e8f0;
      }
      
      td {
        padding: 10px 12px;
        border: 1px solid #e2e8f0;
      }
      
      tr:nth-child(even) {
        background: #f8fafc;
      }
      
      ul, ol {
        margin: 12px 0;
        padding-left: 24px;
      }
      
      li {
        margin: 6px 0;
      }
      
      .section {
        margin: 24px 0;
      }
      
      .footer {
        margin-top: 40px;
        padding-top: 16px;
        border-top: 2px solid #e5e7eb;
        font-size: 12px;
        color: #64748b;
        text-align: center;
      }
      
      .badge {
        display: inline-block;
        padding: 4px 8px;
        border-radius: 4px;
        font-size: 12px;
        font-weight: 600;
      }
      
      .badge-critical { background: #fca5a5; color: #7f1d1d; }
      .badge-high { background: #fed7aa; color: #7c2d12; }
      .badge-medium { background: #fef08a; color: #713f12; }
      .badge-low { background: #bbf7d0; color: #14532d; }
      
      pre {
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 4px;
        padding: 12px;
        overflow-x: auto;
        font-size: 13px;
      }
    </style>
  `

  static generateHTML(data: PDFReportData): string {
    const { title, subtitle, date, sections, metadata } = data

    let html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  ${this.styles}
</head>
<body>
  <div class="report">
    <h1>${title}</h1>
    ${subtitle ? `<p style="font-size: 18px; color: #64748b; margin-top: -4px;">${subtitle}</p>` : ''}
    
    <div class="metadata">
      <div class="metadata-item">
        <span class="metadata-label">Generated:</span>
        <span>${date}</span>
      </div>
      ${metadata ? Object.entries(metadata).map(([key, value]) => `
        <div class="metadata-item">
          <span class="metadata-label">${this.formatLabel(key)}:</span>
          <span>${value}</span>
        </div>
      `).join('') : ''}
    </div>
`

    sections.forEach(section => {
      html += this.renderSection(section)
    })

    html += `
    <div class="footer">
      <p>This report was generated by RACAP - Remote Automated Compliance Audit Platform</p>
      <p>© ${new Date().getFullYear()} DigiTruce Security Platform. All rights reserved.</p>
    </div>
  </div>
  
  <script>
    // Auto-print on load
    window.onload = function() {
      // Delay to ensure styles are loaded
      setTimeout(() => {
        window.print();
      }, 500);
    };
  </script>
</body>
</html>
`
    return html
  }

  private static renderSection(section: PDFSection): string {
    const { title, content, type = 'text' } = section

    let html = `<div class="section"><h2>${title}</h2>`

    switch (type) {
      case 'table':
        html += this.renderTable(content as any[])
        break
      case 'list':
        html += this.renderList(content as string[])
        break
      case 'text':
      default:
        if (typeof content === 'string') {
          html += `<p>${content}</p>`
        } else if (Array.isArray(content)) {
          html += content.map(item => `<p>${item}</p>`).join('')
        }
    }

    html += '</div>'
    return html
  }

  private static renderTable(rows: { [key: string]: any }[]): string {
    if (!rows || rows.length === 0) return '<p>No data available</p>'

    const headers = Object.keys(rows[0])
    
    let html = '<table><thead><tr>'
    headers.forEach(header => {
      html += `<th>${this.formatLabel(header)}</th>`
    })
    html += '</tr></thead><tbody>'

    rows.forEach(row => {
      html += '<tr>'
      headers.forEach(header => {
        const value = row[header]
        html += `<td>${this.formatValue(value)}</td>`
      })
      html += '</tr>'
    })

    html += '</tbody></table>'
    return html
  }

  private static renderList(items: string[]): string {
    if (!items || items.length === 0) return '<p>No items</p>'
    
    let html = '<ul>'
    items.forEach(item => {
      html += `<li>${item}</li>`
    })
    html += '</ul>'
    return html
  }

  private static formatLabel(key: string): string {
    return key
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, str => str.toUpperCase())
      .trim()
  }

  private static formatValue(value: any): string {
    if (value === null || value === undefined) return '-'
    if (typeof value === 'boolean') return value ? 'Yes' : 'No'
    if (typeof value === 'object') return JSON.stringify(value)
    
    // Check for severity badges
    if (['critical', 'high', 'medium', 'low'].includes(String(value).toLowerCase())) {
      return `<span class="badge badge-${String(value).toLowerCase()}">${value}</span>`
    }
    
    return String(value)
  }

  static exportToPDF(data: PDFReportData): void {
    const html = this.generateHTML(data)
    const printWindow = window.open('', '_blank')
    
    if (!printWindow) {
      alert('Please allow pop-ups to generate PDF reports')
      return
    }

    printWindow.document.write(html)
    printWindow.document.close()
  }

  static downloadAsHTML(data: PDFReportData, filename: string): void {
    const html = this.generateHTML(data)
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${filename}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  static exportToText(data: PDFReportData): string {
    const { title, subtitle, date, sections, metadata } = data
    
    let text = `${title}\n${'='.repeat(title.length)}\n\n`
    
    if (subtitle) {
      text += `${subtitle}\n\n`
    }
    
    text += `Generated: ${date}\n`
    
    if (metadata) {
      Object.entries(metadata).forEach(([key, value]) => {
        text += `${this.formatLabel(key)}: ${value}\n`
      })
    }
    
    text += '\n'
    
    sections.forEach(section => {
      text += `\n${section.title}\n${'-'.repeat(section.title.length)}\n`
      
      if (typeof section.content === 'string') {
        text += `${section.content}\n`
      } else if (Array.isArray(section.content)) {
        if (section.type === 'table' && section.content.length > 0) {
          section.content.forEach((row, idx) => {
            if (idx === 0) {
              const headers = Object.keys(row).join(' | ')
              text += `${headers}\n`
              text += `${'-'.repeat(headers.length)}\n`
            }
            text += Object.values(row).join(' | ') + '\n'
          })
        } else {
          section.content.forEach(item => {
            text += `- ${item}\n`
          })
        }
      }
    })
    
    text += `\n\n---\nGenerated by RACAP - Remote Automated Compliance Audit Platform\n`
    text += `© ${new Date().getFullYear()} DigiTruce Security Platform\n`
    
    return text
  }

  static downloadAsText(data: PDFReportData, filename: string): void {
    const text = this.exportToText(data)
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${filename}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }
}
